---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: yes

- name: Install Postgresql
  apt:
    pkg: ["postgresql", "postgresql-contrib"]
    state: present
    force_apt_get: yes
