[tool.poetry]
name = "hermes"
version = "0.0.1"
description = "Hermes Marketplace for IoT data"
authors = ["Pavlos Tzianos <pavlos.tzianos@tum.de>"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
