---
- name: Manage SSH users
  user:
    name: hermes 
    shell: /bin/bash
    state: present
    remove: no

- name: Install Python3 and rsync
  apt:
    pkg: [python3, python3-pip, python3-venv, rsync, python3-dev, libpq-dev, nginx]
    state: present
    force_apt_get: yes

- name: copy Hermes code to the server
  synchronize:
    dest: /opt/
    src: ../marketplace
    dirs: yes
    recursive: yes
    rsync_opts:
    - "--exclude=**/.git"
    - "--exclude=**/.idea"
    - "--exclude=**/.mypy_cache"
    - "--exclude=**/.pytest_cache"
    - "--exclude=.coverage"
    - "--exclude=**/*.iml"
    - "--exclude=**/*.db"
    - "--exclude=**/__pycache__"
    - "--exclude=marketplace/src/hermes.egg-info"

- name: Fix owner of /opt/marketplace directory
  file:
    path: /opt/marketplace
    state: directory
    owner: hermes
    recurse: yes

- name: Install poetry
  pip:
    name: poetry
    executable: /usr/bin/pip3

- name: Check that poetry pip is available
  shell: '/bin/su -c "poetry run python3 -Im ensurepip" hermes'
  ignore_errors: yes
  register: poetry_pip
  args:
    chdir: /opt/marketplace

- name: Get poetry virtualenv home
  shell: '/bin/su -c "poetry config settings.virtualenvs.path" hermes | tr -d \"'
  register: poetry_venv_home
  args:
    chdir: /opt/marketplace

- debug: msg={{ poetry_venv_home.stdout }}

- name: Initialize poetry venv manually so that it contains Pip
  shell: '/bin/su -c "python3 -m venv {{ poetry_venv_home.stdout }}" hermes'
  when: poetry_pip.rc != 0
  args:
    chdir: /opt/marketplace

- name: Install Hermes API server
  shell: '/bin/su -c "poetry install --no-dev --extras prod --extras pg" hermes'
  args:
    chdir: /opt/marketplace

- name: Update haproxy configuration
  copy:
    src: files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Update APK for API <= 23
  copy:
    src: files/hermes_client_lte_23.apk
    dest: /var/www/hermes/apk/hermes_client_lte_23.apk
    owner: hermes

- name: Update APK for API >= 24
  copy:
    src: files/hermes_client_gte_24.apk
    dest: /var/www/hermes/apk/hermes_client_gte_24.apk
    owner: hermes

- name: Deploy Hermes configuration
  copy:
    src: files/hermes.cfg
    dest: /etc/hermes/hermes.cfg
    owner: hermes

- name: Deploy Hermes systemd service file
  copy:
    src: files/marketplace.service
    dest: /etc/hermes/marketplace.service
    owner: hermes
  register: hermes_service_file

- name: Start Hermes service
  systemd:
    name: marketplace
    state: started
    daemon_reload: yes
  when: not hermes_service_file.changed

- name: Restart Hermes service
  systemd:
    name: marketplace
    state: restarted
    daemon_reload: yes
  when: hermes_service_file.changed

- name: Deploy NGINX configuration for static files
  copy:
    src: files/hermes-static.conf
    dest: /etc/nginx/sites-available/hermes-static.conf

- name: Enable NGINX Hermes static files
  file:
    src: /etc/nginx/sites-available/hermes-static.conf
    dest: /etc/nginx/sites-enabled/hermes-static.conf
    state: link

- name: Disable default site of NGINX
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Start NGINX service
  systemd:
    name: nginx
    state: started
